spring:
  datasource:
    driver-class-name: org.postgresql.Driver
#    url: jdbc:postgresql://localhost:5432/Imker
    url: ${SPRING_DATASOURCE_URL}
    username: postgres
#    username: ${SPRING_DATASOURCE_NAME}
    password: root
#    password: ${SPRING_DATASOURCE_PASSWORD}

    hikari:
      connectionTimeout: 20000
      minimumIdle: 10
      maximumPoolSize: 20
      idleTimeout: 300000
      maxLifetime: 1800000

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate.format_sql: true
      hibernate.use_sql_comments: true

  mvc:
    cors:
      allowed-origins:
        - "*"


# DigitalOcean Spaces settings
aws:
  accessKeyId: ${DIGITAL_OCEAN_S3_ACCESS_KEY}
  secretKey: ${DIGITAL_OCEAN_S3_SECRET_KEY}
  s3:
    bucketName: imker
    endpointUrl: ${DIGITAL_OCEAN_S3_ENDPOINT_URL}

#logging:
#  level:
#    org:
#      springframework:
#        security: TRACE

users:
  sort:
    fields: name,plz,role,state,id
  filter:
    fields: role,state
  page:
    size: 3

events:
  sort:
    fields: dateStart
  filter:
    fields: dateStart

files:
  upload:
    path: uploads/
